spring.application.name=TravelMate
spring.datasource.url=jdbc:mysql://localhost:3306/travelmate_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Salman@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret
travelmate.app.jwtSecret=travelmateSecretKeyForJwtAuthenticationSpringSecuritySpringBoot3App2026
travelmate.app.jwtExpirationMs=86400000

# Server port
server.port=8080
